[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "peacemaker4"
authors = [{name = "Katrin Drysch", email = "s6kadrys@uni-bonn.de"}]
dynamic = ["version", "description"]
