[n1]
  composition = [1, 0]
  monomer = []
  volume = 73.483422963
  sigma = 1
  energy = 0.0
  coordinates = "../../clusters/n1.xyz"
  frequencies = "../../clusters/n1.flist" #test1

[n2-1]  #test2
  composition = [2, 0]
  sigma = "True"
  energy = -22.811893045
  coordinates = "../../clusters/n2-1.xyz"
  frequencies = "../../clusters/n2-1.flist"

#test3
[n3-1]
  composition = [3, 0]
  sigma = 1
  energy = -51.107169095
  coordinates = "../../clusters/n3-1.xyz"
  frequencies = "../../clusters/n3-1.flist"

[n4-1]
  composition = [4, 0]
  sigma = 1
  energy = -79.95046576
  coordinates = "../../clusters/n4-1.xyz"
  frequencies = "../../clusters/n4-1.flist"

[n4-2]
  composition = [4, 0]
  sigma = 1
  energy = -79.37574381
  coordinates = "../../clusters/n4-2.xyz"
  frequencies = "../../clusters/n4-2.flist"

[n5-1]
  composition = [5, 0]
  sigma = 1
  energy = -109.543605225
  coordinates = "../../clusters/n5-1.xyz"
  frequencies = "../../clusters/n5-1.flist"

[n5-2]
  composition = [5, 0]
  sigma = 1
  energy = -104.733426675
  coordinates = "../../clusters/n5-2.xyz"
  frequencies = "../../clusters/n5-2.flist"

[n5-3]
  composition = [5, 0]
  sigma = 1
  energy = -101.943465355
  coordinates = "../../clusters/n5-3.xyz"
  frequencies = "../../clusters/n5-3.flist"

[n6-1]
  composition = [6, 0]
  sigma = 1
  energy = -143.98672582
  coordinates = "../../clusters/n6-1.xyz"
  frequencies = "../../clusters/n6-1.flist"

[n6-2]
  composition = [6, 0]
  sigma = 1
  energy = -137.813781495
  coordinates = "../../clusters/n6-2.xyz"
  frequencies = "../../clusters/n6-2.flist"

[n6-3]
  composition = [6, 0]
  sigma = 1
  energy = -134.136611215
  coordinates = "../../clusters/n6-3.xyz"
  frequencies = "../../clusters/n6-3.flist"

[b1]
  composition = [0, 1]
  monomer = []
  volume = 156.92883623
  sigma = 1
  energy = 0.0
  coordinates = "../../clusters/b1.xyz"
  frequencies = "../../clusters/b1.flist"

[b2-1]
  composition = [0, 2]
  sigma = 1
  energy = -17.21692629
  coordinates = "../../clusters/b2-1.xyz"
  frequencies = "../../clusters/b2-1.flist"

[b2-2]
  composition = [0, 2]
  sigma = 1
  energy = -17.21409075
  coordinates = "../../clusters/b2-2.xyz"
  frequencies = "../../clusters/b2-2.flist"

[b3-1]
  composition = [0, 3]
  sigma = 1
  energy = -31.262589895
  coordinates = "../../clusters/b3-1.xyz"
  frequencies = "../../clusters/b3-1.flist"

[b4-1]
  composition = [0, 4]
  sigma = 1
  energy = -53.44856374
  coordinates = "../../clusters/b4-1.xyz"
  frequencies = "../../clusters/b4-1.flist"

[b5-1]
  composition = [0, 5]
  sigma = 1
  energy = -79.17662589
  coordinates = "../../clusters/b5-1.xyz"
  frequencies = "../../clusters/b5-1.flist"

[b5-2]
  composition = [0, 5]
  sigma = 1
  energy = -76.33294684
  coordinates = "../../clusters/b5-2.xyz"
  frequencies = "../../clusters/b5-2.flist"

[b6-1]
  composition = [0, 6]
  sigma = 1
  energy = -106.00282967
  coordinates = "../../clusters/b6-1.xyz"
  frequencies = "../../clusters/b6-1.flist"

[b6-2]
  composition = [0, 6]
  sigma = 1
  energy = -102.11483174
  coordinates = "../../clusters/b6-2.xyz"
  frequencies = "../../clusters/b6-2.flist"

[b6-3]
  composition = [0, 6]
  sigma = 1
  energy = -101.47583755
  coordinates = "../../clusters/b6-3.xyz"
  frequencies = "../../clusters/b6-3.flist"

[n1b1-1]
  composition = [1, 1]
  sigma = 1
  energy = -12.693268555
  coordinates = "../../clusters/n1b1-1.xyz"
  frequencies = "../../clusters/n1b1-1.flist"

[n1b2-1]
  composition = [1, 2]
  sigma = 1
  energy = -30.91878067
  coordinates = "../../clusters/n1b2-1.xyz"
  frequencies = "../../clusters/n1b2-1.flist"

[n1b3-1]
  composition = [1, 3]
  sigma = 1
  energy = -51.533025195
  coordinates = "../../clusters/n1b3-1.xyz"
  frequencies = "../../clusters/n1b3-1.flist"

[n1b4-1]
  composition = [1, 4]
  sigma = 1
  energy = -74.630388855
  coordinates = "../../clusters/n1b4-1.xyz"
  frequencies = "../../clusters/n1b4-1.flist"

[n1b5-1]
  composition = [1, 5]
  sigma = 1
  energy = -99.1378298
  coordinates = "../../clusters/n1b5-1.xyz"
  frequencies = "../../clusters/n1b5-1.flist"

[n1b5-2]
  composition = [1, 5]
  sigma = 1
  energy = -97.533307985
  coordinates = "../../clusters/n1b5-2.xyz"
  frequencies = "../../clusters/n1b5-2.flist"

[n2b1-1]
  composition = [2, 1]
  sigma = 1
  energy = -39.084584515
  coordinates = "../../clusters/n2b1-1.xyz"
  frequencies = "../../clusters/n2b1-1.flist"

[n2b2-1]
  composition = [2, 2]
  sigma = 1
  energy = -57.594254495
  coordinates = "../../clusters/n2b2-1.xyz"
  frequencies = "../../clusters/n2b2-1.flist"

[n2b2-2]
  composition = [2, 2]
  sigma = 1
  energy = -55.432732855
  coordinates = "../../clusters/n2b2-2.xyz"
  frequencies = "../../clusters/n2b2-2.flist"

[n2b3-1]
  composition = [2, 3]
  sigma = 1
  energy = -81.343634825
  coordinates = "../../clusters/n2b3-1.xyz"
  frequencies = "../../clusters/n2b3-1.flist"

[n2b3-2]
  composition = [2, 3]
  sigma = 1
  energy = -76.971967285
  coordinates = "../../clusters/n2b3-2.xyz"
  frequencies = "../../clusters/n2b3-2.flist"

[n2b4-1]
  composition = [2, 4]
  sigma = 1
  energy = -94.957955035
  coordinates = "../../clusters/n2b4-1.xyz"
  frequencies = "../../clusters/n2b4-1.flist"

[n2b4-2]
  composition = [2, 4]
  sigma = 1
  energy = -92.198291985
  coordinates = "../../clusters/n2b4-2.xyz"
  frequencies = "../../clusters/n2b4-2.flist"

[n3b1-1]
  composition = [3, 1]
  sigma = 1
  energy = -70.99441267
  coordinates = "../../clusters/n3b1-1.xyz"
  frequencies = "../../clusters/n3b1-1.flist"

[n3b2-1]
  composition = [3, 2]
  sigma = 1
  energy = -91.76663353
  coordinates = "../../clusters/n3b2-1.xyz"
  frequencies = "../../clusters/n3b2-1.flist"

[n3b2-2]
  composition = [3, 2]
  sigma = 1
  energy = -86.43209012
  coordinates = "../../clusters/n3b2-2.xyz"
  frequencies = "../../clusters/n3b2-2.flist"

[n3b3-1]
  composition = [3, 3]
  sigma = 1
  energy = -111.54898838
  coordinates = "../../clusters/n3b3-1.xyz"
  frequencies = "../../clusters/n3b3-1.flist"


[n3b3-3]
  composition = [3, 3]
  sigma = 1
  energy = -106.92957866
  coordinates = "../../clusters/n3b3-3.xyz"
  frequencies = "../../clusters/n3b3-3.flist"

[n3b3-4]
  composition = [3, 3]
  sigma = 1
  energy = -102.841228825
  coordinates = "../../clusters/n3b3-4.xyz"
  frequencies = "../../clusters/n3b3-4.flist"

[n4b1-1]
  composition = [4, 1]
  sigma = 1
  energy = -96.001643795
  coordinates = "../../clusters/n4b1-1.xyz"
  frequencies = "../../clusters/n4b1-1.flist"

[n4b2-1]
  composition = [4, 2]
  sigma = 1
  energy = -117.468729485
  coordinates = "../../clusters/n4b2-1.xyz"
  frequencies = "../../clusters/n4b2-1.flist"

[n4b2-2]
  composition = [4, 2]
  sigma = 1
  energy = -111.743459165
  coordinates = "../../clusters/n4b2-2.xyz"
  frequencies = "../../clusters/n4b2-2.flist"

[n5b1-1]
  composition = [5, 1]
  sigma = 1
  energy = -129.83664608
  coordinates = "../../clusters/n5b1-1.xyz"
  frequencies = "../../clusters/n5b1-1.flist"

