[system]
  components = [2]

[qce]
  amf = [0.0, 2.0, 21] # J*m^3/mol
  bxv = [0.1, 2.1, 21]
  optimizer = 11
  rotor_cutoff = 100

[ensemble]
  temperature = [280.0, 550.0, 271] # K
  pressure = [1.01325] # bar
  monomer_amounts = [0.2, 0.8] # mol

[reference]
  density = [298.15, 1.014852]
  phase_transition = [378.15]

[output]
  contributions = true
